import { ChangeEvent, useMemo, useState } from 'react';
import { blankDraft, dayGroup, exercises, exercisesForDay, nextDay, parseNumber, sessionReps, sessionVolume, setVolume, type DayType, type Draft, type WorkoutSession, type WorkoutState } from './workout';
import { readState, saveState, validateImport } from './services/storage/workoutStorage';

const dateText = (date: string) => new Intl.DateTimeFormat('es-ES', { dateStyle: 'long' }).format(new Date(`${date}T12:00:00`));
const today = () => new Date().toISOString().slice(0, 10);
const fmt = (value: number) => `${Math.round(value).toLocaleString('es-ES')} kg`;
const id = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const App = () => {
  const [state, setState] = useState<WorkoutState>(readState); const [screen, setScreen] = useState<'home'|'workout'|'history'|'progress'|'success'|'detail'>('home');
  const [pendingDay, setPendingDay] = useState<DayType | null>(null); const [editing, setEditing] = useState<string | null>(null); const [selectedExercise, setSelectedExercise] = useState(exercises[0].id); const [notice, setNotice] = useState(''); const [completed, setCompleted] = useState<WorkoutSession | null>(null);
  const update = (next: WorkoutState) => { setState(next); saveState(next); };
  const recommendation = nextDay(state.sessions); const draft = state.draft;
  const start = (day: DayType) => { if (draft) { setPendingDay(day); return; } update({ ...state, draft: blankDraft(day) }); setEditing(null); setScreen('workout'); };
  const openDraft = () => { if (draft) { setEditing(null); setScreen('workout'); } };
  const replaceDraft = () => { if (pendingDay) { update({ ...state, draft: blankDraft(pendingDay) }); setEditing(null); setScreen('workout'); } setPendingDay(null); };
  const mutateDraft = (fn: (d: Draft) => Draft) => { if (draft) update({ ...state, draft: fn(draft) }); };
  const editSession = (session: WorkoutSession) => { update({ ...state, draft: { dayType: session.dayType, startedAt: session.completedAt, exercises: session.exercises } }); setEditing(session.id); setScreen('workout'); };
  const finish = () => { if (!draft) return; const invalid = draft.exercises.some((ex) => ex.sets.some((set) => parseNumber(set.weight) === null || parseNumber(set.reps) === null)); if (invalid) { setNotice('Completa cada peso y repetición con números válidos (por ejemplo 22,5 y 8).'); return; }
    if (editing) { const previous = state.sessions.find((session) => session.id === editing)!; const changed = { ...previous, exercises: draft.exercises }; update({ ...state, sessions: state.sessions.map((session) => session.id === editing ? changed : session), draft: undefined }); setCompleted(changed); }
    else { const started = new Date(draft.startedAt); const session: WorkoutSession = { id: id(), date: today(), completedAt: new Date().toISOString(), durationMinutes: Math.max(1, Math.round((Date.now() - started.getTime()) / 60000)), dayType: draft.dayType, exercises: draft.exercises }; update({ ...state, sessions: [...state.sessions, session], draft: undefined }); setCompleted(session); }
    setEditing(null); setNotice(''); setScreen('success');
  };
  const selected = useMemo(() => state.sessions.flatMap((session) => session.exercises.filter((item) => item.exerciseId === selectedExercise).map((item) => ({ session, item }))), [state.sessions, selectedExercise]);
  const prs = (exerciseId: string) => { const entries = state.sessions.flatMap((session) => session.exercises.filter((ex) => ex.exerciseId === exerciseId).map((ex) => ({ session, ex }))); const sets = entries.flatMap(({ ex }) => ex.sets); const maxWeight = Math.max(0, ...sets.map((set) => parseNumber(set.weight) ?? 0)); const bestSet = sets.reduce((best, set) => (setVolume(exerciseId, set) > setVolume(exerciseId, best) ? set : best), { weight: '', reps: '' }); const volume = Math.max(0, ...entries.map(({ ex }) => ex.sets.reduce((sum, set) => sum + setVolume(exerciseId, set), 0))); return { maxWeight, bestSet, volume }; };
  const totals = useMemo(() => { const now = new Date(); const week = new Date(now); week.setDate(now.getDate() - ((now.getDay() + 6) % 7)); const sameMonth = (d: string) => new Date(d).getMonth() === now.getMonth() && new Date(d).getFullYear() === now.getFullYear(); return { total: state.sessions.length, month: state.sessions.filter((s) => sameMonth(s.date)), volume: state.sessions.reduce((sum,s) => sum + sessionVolume(s), 0), monthVolume: state.sessions.filter(s => sameMonth(s.date)).reduce((sum,s) => sum + sessionVolume(s), 0), weekVolume: state.sessions.filter(s => new Date(s.date) >= week).reduce((sum,s) => sum + sessionVolume(s), 0) }; }, [state.sessions]);
  const importFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; file.text().then((text) => { try { const result = validateImport(JSON.parse(text)); if (typeof result === 'string') setNotice(result); else { update(result); setNotice('Datos importados correctamente.'); } } catch { setNotice('Archivo no válido: no se pudo leer el JSON.'); } }); event.target.value = ''; };
  const download = () => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' })); a.download = 'iron-log-backup.json'; a.click(); URL.revokeObjectURL(a.href); };
  const nav = <nav className="bottom-nav"><button onClick={() => setScreen('home')}>⌂<span>Inicio</span></button><button onClick={() => setScreen('history')}>◷<span>Historial</span></button><button onClick={() => setScreen('progress')}>▥<span>Progreso</span></button></nav>;
  if (screen === 'workout' && draft) return <main className="app-shell"><header><button className="text-button" onClick={() => setScreen('home')}>← Guardado automático</button><b>DÍA {draft.dayType}</b></header><section className="workout-head"><small>{dayGroup(draft.dayType)}</small><h1>{editing ? 'Editar sesión' : 'Entrenamiento en progreso'}</h1><p>{editing ? 'La fecha, duración y orden original se conservarán.' : 'Cada cambio se guarda al instante.'}</p></section>{draft.exercises.map((exercise, exerciseIndex) => { const info = exercises.find((item) => item.id === exercise.exerciseId)!; return <article className="exercise-card" key={exercise.exerciseId}><h2>{info.name}</h2><small>{info.equipment === 'dumbbell' ? 'Peso por mancuerna/lado · volumen ×2' : info.equipment === 'bar' ? 'Peso total de barra' : 'Peso de máquina/cable'}</small>{exercise.sets.map((set, setIndex) => <div className="set-row" key={setIndex}><b>{setIndex + 1}</b><label>Peso<input inputMode="decimal" value={set.weight} onChange={e => mutateDraft(d => ({ ...d, exercises: d.exercises.map((x,i) => i === exerciseIndex ? { ...x, sets: x.sets.map((y,j) => j === setIndex ? { ...y, weight: e.target.value } : y) } : x) }))} placeholder="kg" /></label><label>Reps<input inputMode="numeric" value={set.reps} onChange={e => mutateDraft(d => ({ ...d, exercises: d.exercises.map((x,i) => i === exerciseIndex ? { ...x, sets: x.sets.map((y,j) => j === setIndex ? { ...y, reps: e.target.value } : y) } : x) }))} placeholder="0" /></label>{exercise.sets.length > 1 && <button className="icon" onClick={() => mutateDraft(d => ({ ...d, exercises: d.exercises.map((x,i) => i === exerciseIndex ? { ...x, sets: x.sets.filter((_,j) => j !== setIndex) } : x) }))}>−</button>}</div>)}<button className="add" onClick={() => mutateDraft(d => ({ ...d, exercises: d.exercises.map((x,i) => i === exerciseIndex ? { ...x, sets: [...x.sets, { weight: '', reps: '' }] } : x) }))}>+ Añadir serie</button><textarea value={exercise.notes} placeholder="Notas (opcional)" onChange={e => mutateDraft(d => ({ ...d, exercises: d.exercises.map((x,i) => i === exerciseIndex ? { ...x, notes: e.target.value } : x) }))} /></article>})}{notice && <p className="notice">{notice}</p>}<button className="primary finish" onClick={finish}>{editing ? 'GUARDAR CAMBIOS' : 'FINALIZAR ENTRENAMIENTO'}</button></main>;
  if (screen === 'success' && completed) { const pr = prs(completed.exercises[0]?.exerciseId ?? ''); const first = completed.exercises[0]; return <main className="success"><div className="trophy">🏆</div><small>IRON LOG</small><h1>ENTRENAMIENTO<br /><span>COMPLETADO</span></h1><h2>DÍA {completed.dayType}</h2><p>{dayGroup(completed.dayType)} · {dateText(completed.date)}</p><div className="metrics"><div><b>{completed.exercises.length}</b><small>ejercicios</small></div><div><b>{completed.exercises.reduce((n,e)=>n+e.sets.length,0)}</b><small>series</small></div><div><b>{sessionReps(completed)}</b><small>repeticiones</small></div><div><b>{fmt(sessionVolume(completed))}</b><small>volumen</small></div></div>{completed.durationMinutes && <p>Duración: {completed.durationMinutes} min</p>}{pr.maxWeight > 0 && <div className="pr"><small>NUEVO RÉCORD · mejor peso actual</small><b>{exercises.find(e=>e.id===first.exerciseId)?.name}</b><span>{pr.maxWeight} kg × {pr.bestSet.reps}</span></div>}<button className="primary" onClick={() => setScreen('detail')}>VER DETALLE COMPLETO</button></main>; }
  const sessionDetail = completed ?? state.sessions[0];
  if (screen === 'detail' && sessionDetail) return <main className="app-shell"><button className="text-button" onClick={() => setScreen('history')}>← Historial</button><h1>Día {sessionDetail.dayType}</h1><p>{dateText(sessionDetail.date)} · {fmt(sessionVolume(sessionDetail))}</p>{sessionDetail.exercises.map(ex => <article className="exercise-card" key={ex.exerciseId}><h2>{exercises.find(e=>e.id===ex.exerciseId)?.name}</h2>{ex.sets.map((set,i)=><p key={i}>Serie {i+1}: <b>{set.weight} kg × {set.reps}</b> <small> · {fmt(setVolume(ex.exerciseId,set))}</small></p>)}{ex.notes && <p>{ex.notes}</p>}</article>)}</main>;
  if (screen === 'history') return <main className="app-shell"><header><b>Historial por ejercicio</b></header><h1>Tu evolución</h1><select value={selectedExercise} onChange={e=>setSelectedExercise(e.target.value)}>{exercises.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>{(() => { const p = prs(selectedExercise); return <><div className="metrics"><div><b>{p.maxWeight} kg</b><small>mejor peso</small></div><div><b>{p.bestSet.weight || '—'} × {p.bestSet.reps || '—'}</b><small>mejor serie</small></div><div><b>{fmt(p.volume)}</b><small>mayor volumen</small></div></div><div className="chart"><h2>Evolución de volumen por sesión</h2><div className="bars">{selected.map(({item},i)=><i key={i} style={{height:`${Math.max(8, sessionVolume({exercises:[item]}) / Math.max(1,p.volume)*150)}px`}} title={fmt(sessionVolume({exercises:[item]}))}/>)}</div></div></>})()}{selected.length ? selected.map(({session,item})=><article className="exercise-card" key={session.id}><b>{dateText(session.date)}</b>{item.sets.map((set,i)=><p key={i}>Serie {i+1}: {set.weight} kg × {set.reps} <small>· {fmt(setVolume(item.exerciseId,set))}</small></p>)}</article>):<p className="empty">Aún no hay registros para este ejercicio.</p>}{nav}</main>;
  if (screen === 'progress') { const best = exercises.map(e=>({e,p:prs(e.id)})).sort((a,b)=>b.p.maxWeight-a.p.maxWeight)[0]; return <main className="app-shell"><header><b>Progreso</b></header><h1>Datos con contexto</h1><div className="metrics stats"><div><b>{totals.total}</b><small>entrenamientos totales</small></div><div><b>{totals.month.length}</b><small>este mes</small></div><div><b>{fmt(totals.volume)}</b><small>volumen total</small></div><div><b>{fmt(totals.monthVolume)}</b><small>volumen mensual</small></div><div><b>{fmt(totals.weekVolume)}</b><small>semana actual</small></div><div><b>{totals.month.length ? (totals.month.length / Math.max(1, new Date().getDate()/7)).toFixed(1) : '0'}</b><small>sesiones/semana</small></div></div><div className="chart"><h2>Volumen por sesión</h2><p>Representa el volumen total registrado en cada entrenamiento.</p><div className="bars">{state.sessions.map(s=><i key={s.id} style={{height:`${Math.max(8,sessionVolume(s)/Math.max(1,...state.sessions.map(sessionVolume))*150)}px`}} />)}</div></div><article className="exercise-card"><small>MEJOR PESO GLOBAL</small><h2>{best?.e.name ?? 'Aún sin datos'}</h2><b>{best?.p.maxWeight ?? 0} kg</b><p>Mejor serie: {best?.p.bestSet.weight || '—'} kg × {best?.p.bestSet.reps || '—'}. Mayor progreso: registra más sesiones para comparar evolución.</p></article>{nav}</main>; }
  return <main className="app-shell"><header><b>IRON LOG</b><span>●</span></header><section className="hero"><small>RUTINA 4 DÍAS</small><h1>Entrena con<br /><span>intención.</span></h1><p>Tu siguiente sesión se calcula por el último entrenamiento completado, no por la fecha.</p><div className="next"><small>SIGUIENTE SESIÓN</small><h2>DÍA {recommendation}</h2><p>{dayGroup(recommendation)}</p><button className="primary" onClick={() => start(recommendation)}>COMENZAR DÍA {recommendation}</button></div></section>{draft && <section className="resume"><b>Hay un entrenamiento en progreso.</b><p>Día {draft.dayType}, guardado automáticamente.</p><button className="primary" onClick={openDraft}>CONTINUAR ENTRENAMIENTO</button><button className="text-button" onClick={() => update({...state,draft:undefined})}>DESCARTAR</button></section>}<section><h2>Historial reciente</h2>{state.sessions.length ? state.sessions.slice().sort((a,b)=>new Date(b.completedAt).getTime()-new Date(a.completedAt).getTime()).map(s=><article className="session" key={s.id}><button onClick={()=>{setCompleted(s);setScreen('detail')}}><small>DÍA {s.dayType} · {dateText(s.date)}</small><b>{dayGroup(s.dayType)}</b><span>{fmt(sessionVolume(s))} · {s.exercises.length} ejercicios</span></button><button className="edit" onClick={()=>editSession(s)}>Editar</button></article>) : <p className="empty">Aún no hay entrenamientos. Empieza por Día 1.</p>}</section><section className="backup"><button onClick={download}>Exportar JSON</button><label>Importar JSON<input type="file" accept="application/json" onChange={importFile}/></label>{notice && <p className="notice">{notice}</p>}</section>{pendingDay && <div className="modal"><div><h2>Ya tienes un entrenamiento en progreso.</h2><p>¿Quieres continuar con él o comenzar una nueva sesión?</p><button className="primary" onClick={()=>{setPendingDay(null);openDraft()}}>CONTINUAR</button><button className="text-button" onClick={replaceDraft}>COMENZAR NUEVO</button></div></div>}{nav}</main>;
};
export { App };
